### ISSUE TITLE
Output nucleic acid sequences

### ISSUE THREAD

**Issue by gretchend** [dnasko/frameshift_polisher#1]
Hi-- I was wondering if there was any function that I might be missing to output frameshift corrected nucleic acid sequences along with the amino acid sequences. Thanks!

**Comment by dnasko** [comment]
Hi there, apologies for the delay in reply!

Unfortunately there is no function to produce corrected nucleotide sequences with the protein sequences.

I don't plan on writing a function to do this in the near future, but if I ever do I'll be sure to update this repository with release notes on how to produce the corresponding nucleotide sequences.

Sorry!

**Comment by gretchend** [comment]
Okay! Thanks!
